

export const list=[
    {
        name:"Superman",
        id:1,
        weight:102,
        height:`6'3”`,
        type:'Save me',
        hp:100,
        attack:100,
        defense:100,
        specialAttack:100,
        special:"Homelander Eyes",
        speed:120,
        image: "images/sueprman.jpeg",
        uni:"DC"
    },
    {
        name: "Spiderman",
        id: 2,
        weight: 76, 
        height: `5'10”`,
        type: 'Writers punching bag',
        hp: 85,
        attack: 85,
        defense: 75,
        specialAttack: 90,
        special: "peter-tingle",
        speed:99,
        image: "images/spiderman.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Wolverine",
        id: 3,
        weight: 136, 
        height: `5'3”`,
        type: 'Animal',
        hp: 95,
        attack: 95,
        defense: 90,
        specialAttack: 70,
        special: "healing bub",
        speed:90,
        image: "images/wolverine.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Thor",
        id: 4,
        weight: 290, 
        height: `6'6”`,
        type: 'Used to have Cool hair',
        hp: 110,
        attack: 120,
        defense: 100,
        specialAttack: 120,
        special: "god of hammers",
        speed:80,
        image: "images/thor.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Iron Man",
        id: 5,
        weight: 102, 
        height: `6'1”`,
        type: 'Rich',
        hp: 90,
        attack: 95,
        defense: 100,
        specialAttack: 110,
        special: "genius, Billionare, Playboy,Philanthropist",
        speed:100,
        image: "images/ironmab.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Captain America",
        id: 6,
        weight: 108, 
        height: `6'2”`,
        type: 'Old man',
        hp: 95,
        attack: 90,
        defense: 95,
        specialAttack: 70,
        special: "1900s Racism",
        speed:80,
        image: "images/cap.png",
        uni:"MARVEL"
    },
    {
        name: "Black Widow",
        id: 7,
        weight: 59, 
        height: `5'7”`,
        type: 'Woman',
        hp: 80,
        attack: 85,
        defense: 75,
        specialAttack: 70,
        special: "Only Woman in Avengers",
        speed:70,
        image: "images/bw.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Hawkeye",
        id: 8,
        weight: 91,
        height: `6'1”`,
        type: 'Arrow guy',
        hp: 80,
        attack: 80,
        defense: 70,
        specialAttack: 75,
        special: "He's Him",
        speed:50,
        image: "images/hwakeye.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Falcon",
        id: 9,
        weight: 90, 
        height: `6'0”`,
        type: 'Black',
        hp: 85,
        attack: 80,
        defense: 75,
        specialAttack: 85,
        special: "Cap's sidekick",
        speed:100,
        image: "images/falcon.png",
        uni:"MARVEL"
    },
    {
        name: "Winter Soldier",
        id: 10,
        weight: 118, 
        height: `6'0”`,
        type: 'PTSD',
        hp: 90,
        attack: 95,
        defense: 90,
        specialAttack: 80,
        special: "Trauma",
        speed:90,
        image: "images/ws.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Hulk",
        id: 11,
        weight: 635, 
        height: `7'0”` ,
        type:'Rager',
        hp: 130,
        attack: 140,
        defense: 120,
        specialAttack: 85,
        special: "Smashing people",
        speed:110,
        image: "images/hulk.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Loki",
        id: 12,
        weight: 238, 
        height: `6'4”`,
        type: 'Trickster',
        hp: 95,
        attack: 85,
        defense: 85,
        specialAttack: 115,
        special: "Help me Brother",
        speed:85,
        image: "images/loki.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Batman",
        id: 13,
        weight: 95, 
        height: `6'2”`,
        type: 'Vigillante Orphan',
        hp: 90,
        attack: 85,
        defense: 95,
        specialAttack: 80,
        special: "I'm Rich",
        speed:99,
        image: "images/bm.jpeg",
        uni:"DC"
    },
    {
        name: "Joker",
        id: 14,
        weight: 86, 
        height: `6'0”`,
        type: 'Chaos',
        hp: 80,
        attack: 75,
        defense: 70,
        specialAttack: 95,
        special: "Annoying Batman",
        speed:30,
        image: "images/joker.jpeg",
        uni:"DC"
    },
    {
        name: "Wonder Woman",
        id: 15,
        weight: 75, 
        height: `6'0”`,
        type: 'Woman',
        hp: 110,
        attack: 115,
        defense: 110,
        specialAttack: 100,
        special: "Represented by Worst Actor",
        speed:100,
        image: "images/ww.jpeg",
        uni:"DC"
    },
    {
        name: "Martian Manhunter",
        id: 16,
        weight: 135, 
        height: `6'7”`,
        type: 'Cool Dude',
        hp: 115,
        attack: 110,
        defense: 105,
        specialAttack: 120,
        special: "Depression",
        speed:110,
        image: "images/i16.jpeg",
        uni:"DC"
    },
    {
        name: "Cyborg",
        id: 17,
        weight: 173, 
        height: `6'6”`,
        type: 'Bad Parents',
        hp: 105,
        attack: 100,
        defense: 110,
        specialAttack: 115,
        special: "Bad looks",
        speed:50,
        image: "images/i17.jpeg",
        uni:"DC"
    },
    {
        name: "Flash",
        id: 18,
        weight: 86, 
        height: `6'0”`,
        type: 'Your Mom',
        hp: 90,
        attack: 85,
        defense: 75,
        specialAttack: 105,
        special: "Worse than Wally West",
        speed:`∞`,
        image: "images/i18.png",
        uni:"DC"
    },
    {
        name: "Reverse Flash",
        id: 19,
        weight: 86, 
        height: `6'0”`,
        type:  `Flash's Mom`,
        hp: 95,
        attack: 90,
        defense: 80,
        specialAttack: 115,
        special: "Love for Barry allen",
        speed:`∞`,
        image: "images/i19.jpeg",
        uni:"DC"
    },
    {
        name: "Aquaman",
        id: 20,
        weight: 106, 
        height: `6'1”`,
        type: 'Diversity guy in group',
        hp: 105,
        attack: 100,
        defense: 100,
        specialAttack: 90,
        special: "A trident with 5 dents",
        speed:90,
        image: "images/i20.jpeg",
        uni:"DC"
    },
    {
        name: "Robin",
        id: 21,
        weight: 80, 
        height: `5'10”`,
        type: 'Bats sidekick',
        hp: 80,
        attack: 75,
        defense: 70,
        specialAttack: 70,
        special: "No kill code",
        speed:65,
        image: "images/i21.jpeg",
        uni:"DC"
    },
    {
        name: "Punisher",
        id: 22,
        weight: 91, 
        height: `6'1”`,
        type: 'Steel Balls',
        hp: 85,
        attack: 95,
        defense: 80,
        specialAttack: 85,
        special: "Got that dog in him",
        speed:85,
        image: "images/i22.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Star-Lord",
        id: 23,
        weight: 88, 
        height: `6'2”`,
        type: 'Weird Parents',
        hp: 85,
        attack: 80,
        defense: 80,
        specialAttack: 85,
        special: "Green girls",
        speed:60,
        image: "images/i23.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Gamora",
        id: 24,
        weight: 72, 
        height: `5'11”`,
        type: 'Woman',
        hp: 90,
        attack: 95,
        defense: 85,
        specialAttack: 80,
        special: "Only Woman in Gaurdians",
        speed:82,
        image: "images/i24.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Drax",
        id: 25,
        weight: 136, 
        height: `6'6”`,
        type: 'Comic Relief Character',
        hp: 95,
        attack: 100,
        defense: 90,
        specialAttack: 70,
        special: "Invisibility",
        speed:0,
        image: "images/i25.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Rocket Raccoon",
        id: 26,
        weight: 25, 
        height: `3'1”`,
        type: 'Childhood Trauma',
        hp: 75,
        attack: 80,
        defense: 65,
        specialAttack: 95,
        special: "Bucky's Arm",
        speed:50,
        image: "images/i26.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Groot",
        id: 27,
        weight: 283, 
        height: `7'10”`,
        type: "Stormbreaker's handle",
        hp: 100,
        attack: 90,
        defense: 105,
        specialAttack: 85,
        special: "I Am Groot",
        speed:30,
        image: "images/i27.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Mantis",
        id: 28,
        weight: 56, 
        height: `5'6”`,
        type: "Ego's Doll",
        hp: 80,
        attack: 65,
        defense: 70,
        specialAttack: 95,
        special: "2nd Comic relief Character",
        speed:10,
        image: "images/i28.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Nebula",
        id: 29,
        weight: 79,
        height: `6'1”`,
        type: 'Bad Parents',
        hp: 90,
        attack: 95,
        defense: 90,
        specialAttack: 85,
        special: "Thanos picked Nice eyes",
        speed:70,
        image: "images/i29.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Thanos",
        id: 30,
        weight: 447,
        height: `8'0”`,
        type: 'Visionary',
        hp: 150,
        attack: 140,
        defense: 135,
        specialAttack: 130,
        special: "Fine, he'll do it by Himself",
        speed:95,
        image: "images/i30.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Deadpool",
        id: 31,
        weight: 95,
        height: `6'2”`,
        type: 'Cancerous',
        hp: 100,
        attack: 90,
        defense: 85,
        specialAttack: 85,
        special: "You're Probably Thinking why I didn't break the 4th wall",
        speed:90,
        image: "images/i31.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Professor X",
        id: 32,
        weight: 86,
        height: `6'0”`,
        type: 'Non Racist Guy in the group',
        hp: 85,
        attack: 40,
        defense: 60,
        specialAttack: 120,
        special: "Non Working legs",
        speed:5,
        image: "images/i32.jpg",
        uni:"MARVEL"
    },
    {
        name: "Magneto",
        id: 33,
        weight: 86,
        height: `6'2”`,
        type: 'Racist Guy in the Group',
        hp: 100,
        attack: 90,
        defense: 95,
        specialAttack: 125,
        special: "Kill Them Humans",
        speed:40,
        image: "images/i33.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Mystique",
        id: 34,
        weight: 62,
        height: `5'10”`,
        type: 'Woman/Man',
        hp: 85,
        attack: 85,
        defense: 80,
        specialAttack: 90,
        special: "Ugliness",
        speed:50,
        image: "images/i34.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Storm",
        id: 35,
        weight: 66,
        height: `5'11”`,
        type: 'Unused Character',
        hp: 95,
        attack: 90,
        defense: 85,
        specialAttack: 120,
        special: "Thor but Not Thor",
        speed:70,
        image: "images/i35.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Cyclops",
        id: 36,
        weight: 91,
        height: `6'0”`,
        type: 'Cool Glasses',
        hp: 85,
        attack: 80,
        defense: 75,
        specialAttack: 110,
        special: "Third Wheel of jean and Wolverine",
        speed:40,
        image: "images/i36.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Jean Grey",
        id: 37,
        weight: 59,
        height: `5'6”`,
        type: 'Woman',
        hp: 80,
        attack: 70,
        defense: 70,
        specialAttack: 120,
        special: "Split Personality",
        speed:80,
        image: "images/i37.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Beast",
        id: 38,
        weight: 108,
        height: `6'3”`,
        type: 'Weird Feet',
        hp: 90,
        attack: 90,
        defense: 85,
        specialAttack: 95,
        special: "Nerd",
        speed:60,
        image: "images/i38.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Nightcrawler",
        id: 39,
        weight: 75,
        height: `5'9”`,
        type: 'Ugly dude',
        hp: 80,
        attack: 75,
        defense: 70,
        specialAttack: 85,
        special: "Teleport but of no use",
        speed:`∞`,
        image: "images/i39.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Colossus",
        id: 40,
        weight: 150,
        height: `7'1”`,
        type: 'Russian Balls of Steel',
        hp: 110,
        attack: 115,
        defense: 120,
        specialAttack: 75,
        special: "Russian accent",
        speed:75,
        image: "images/i40.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Phoenix",
        id: 41,
        weight: 59,
        height: `5'6”`,
        type: 'Best part of Jean Grey',
        hp: 100,
        attack: 90,
        defense: 85,
        specialAttack: 150,
        special: "Childhood Trauma",
        speed:110,
        image: "images/i41.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Odin",
        id: 42,
        weight: 290,
        height: `6'6”`,
        type: 'Bad Parent',
        hp: 150,
        attack: 130,
        defense: 130,
        specialAttack: 140,
        special: "Stealing Children",
        speed:60,
        image: "images/i42.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Green Goblin",
        id: 43,
        weight: 95,
        height: `6'0”`,
        type: 'Split Personality',
        hp: 90,
        attack: 95,
        defense: 80,
        specialAttack: 100,
        special: "Laughing on Spiderman",
        speed:105,
        image: "images/i43.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Doctor Octopus",
        id: 44,
        weight: 95,
        height: `6'0”`,
        type: 'Ironman built it in a Cave',
        hp: 90,
        attack: 85,
        defense: 85,
        specialAttack: 100,
        special: "Power of Sun in the Palm of his Hands",
        speed:98,
        image: "images/i44.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Electro",
        id: 45,
        weight: 91,
        height: `6'2”`,
        type: 'Spiderman Forgot his birthday',
        hp: 85,
        attack: 80,
        defense: 75,
        specialAttack: 110,
        special: "Singing Happy Birthday",
        speed:105,
        image: "images/i45.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Sandman",
        id: 46,
        weight: 110,
        height: `6'3”`,
        type: 'Uncle Ben Killer',
        hp: 95,
        attack: 90,
        defense: 100,
        specialAttack: 75,
        special: "With Great Power comes Great Gun shootings",
        speed:90,
        image: "images/i46.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Vulture",
        id: 47,
        weight: 88,
        height: `5'11”`,
        type: 'Flying man',
        hp: 80,
        attack: 85,
        defense: 75,
        specialAttack: 85,
        special: "Short term Memory Loss",
        speed:105,
        image: "images/i47.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Mysterio",
        id: 48,
        weight: 84,
        height: `6'0”`,
        type: 'Con Artist',
        hp: 80,
        attack: 70,
        defense: 75,
        specialAttack: 105,
        special: "Fish Bowl for a head",
        speed:105,
        image: "images/i48.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Kraven the Hunter",
        id: 49,
        weight: 102,
        height: `6'1”`,
        type: 'Animal',
        hp: 90,
        attack: 95,
        defense: 85,
        specialAttack: 80,
        special: "Never hunting a Shower",
        speed:85,
        image: "images/i49.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Mr Fantastic",
        id: 50,
        weight: 88,
        height: `6'2”`,
        type: 'Women Love Him',
        hp: 90,
        attack: 80,
        defense: 85,
        specialAttack: 95,
        special: "Nerd",
        speed:100,
        image: "images/i50.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Invisible Woman",
        id: 51,
        weight: 68,
        height: `5'9”`,
        type: 'Only Woman in F4',
        hp: 85,
        attack: 75,
        defense: 80,
        specialAttack: 100,
        special: "Nose Bleeds Everytime Uses Powers",
        speed:79,
        image: "images/i51.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Human Torch",
        id: 52,
        weight: 80,
        height: `6'0”`,
        type: 'Fun guy',
        hp: 85,
        attack: 85,
        defense: 75,
        specialAttack: 110,
        special: "Flame on",
        speed:105,
        image: "images/i52.jpeg",
        uni:"MARVEL"
    },
    {
        name: "The Thing",
        id: 53,
        weight: 180,
        height: `6'6”`,
        type: `It's Okay Dude`,
        hp: 110,
        attack: 115,
        defense: 120,
        specialAttack: 70,
        special: "It's Clobberin Time",
        speed:60,
        image: "images/i53.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Doctor Doom",
        id: 54,
        weight: 102,
        height: `6'2”`,
        type: 'Another Level of Nerd/Better Than Reed',
        hp: 100,
        attack: 95,
        defense: 100,
        specialAttack: 115,
        special: "He is Better than you",
        speed:100,
        image: "images/i54.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Galactus",
        id: 55,
        weight: 10000,
        height: `28'0”`,
        type: 'Big Guy',
        hp: 500,
        attack: 500,
        defense: 450,
        specialAttack: 550,
        special: "Getting Defeated by Teleportation",
        speed:200,
        image: "images/i55.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Mole Man",
        id: 56,
        weight: 75,
        height: `5'7”`,
        type: 'Racist guy',
        hp: 70,
        attack: 65,
        defense: 60,
        specialAttack: 80,
        special: "Shower once a year",
        speed:30,
        image: "images/i56.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Living Tribunal",
        id: 57,
        weight: "Immeasurable",
        height: "Multiversal",
        type: 'Four Face',
        hp: 200,
        attack: 150,
        defense: 200,
        specialAttack: 200,
        special: "Unjust Judgement",
        speed:`∞`,
        image: "images/i57.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Beyonder",
        id: 58,
        weight: 0,
        height: `∞`,
        type: 'Crazy Guy',
        hp: 1000,
        attack: 1000,
        defense: 1000,
        specialAttack: 1000,
        special: "Reality can be Whatever he wants",
        speed:`∞`,
        image: "images/i58.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Taskmaster",
        id: 59,
        weight: 95,
        height: `6'3”`,
        type: 'Obsession over Spiderman',
        hp: 85,
        attack: 90,
        defense: 85,
        specialAttack: 80,
        special: "Cheat Master",
        speed:100,
        image: "images/i59.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Shazam",
        id: 60,
        weight: 95,
        height: `6'3”`,
        type: 'kid or adult?',
        hp: 110,
        attack: 115,
        defense: 100,
        specialAttack: 105,
        special: "Bro's Name",
        speed:90,
        image: "images/i60.jpeg",
        uni:"DC"
    },
    {
        name: "Captain Marvel",
        id: 61,
        weight: 75,
        height: `5'11”`,
        type: 'Woman',
        hp: 110,
        attack: 115,
        defense: 95,
        specialAttack: 120,
        special: "Feminist Woman that judges you",
        speed:105,
        image: "images/i61.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Daredevil",
        id: 62,
        weight: 77,
        height: `6'0”`,
        type: 'Blind dude with great Hearing',
        hp: 85,
        attack: 90,
        defense: 80,
        specialAttack: 75,
        special: "Saul goodman of marvel",
        speed:75,
        image: "images/i62.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Venom",
        id: 63,
        weight: 102,
        height: `6'3”`,
        type: 'black goo',
        hp: 100,
        attack: 110,
        defense: 90,
        specialAttack: 90,
        special: "Heads, livers, Cannibalism",
        speed:99,
        image: "images/i63.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Omni Man",
        id: 64,
        weight: 200,
        height: `6'2”`,
        type: "Are you Sure?",
        hp: 120,
        attack: 120,
        defense: 110,
        specialAttack: 100,
        special: "Pet Debbie",
        speed:120,
        image: "images/i64.jpeg",
        uni:"INVINCIBLE"
    },
    {
        name: "Scarlet Witch",
        id: 65,
        weight: 60,
        height: `5'6”`,
        type: 'robot lover',
        hp: 90,
        attack: 70,
        defense: 75,
        specialAttack: 130,
        special: "evil witch things",
        speed:100,
        image: "images/i65.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Quicksilver",
        id: 66,
        weight: 72,
        height: `5'11”`,
        type: "fast but he's no Flash",
        hp: 85,
        attack: 80,
        defense: 75,
        specialAttack: 95,
        special: "He Ain't see that",
        speed:`∞`,
        image: "images/i66.jpeg",
        uni:"MARVEL/DC"
    },
    {
        name: "Doctor Strange",
        id: 67,
        weight: 82,
        height: `6'2”`,
        type: 'Average Doctor Experience',
        hp: 95,
        attack: 80,
        defense: 85,
        specialAttack: 130,
        special: "His name is Strange",
        speed:90,
        image: "images/i67.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Black Panther",
        id: 68,
        weight: 91,
        height: `6'0”`,
        type: 'Black',
        hp: 95,
        attack: 100,
        defense: 90,
        specialAttack: 85,
        special: "Played by Chadwick Boseman",
        speed:85,
        image: "images/i68.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Vision",
        id: 69,
        weight: 135,
        height: `6'3”`,
        type: 'Phillosphy final Boss',
        hp: 100,
        attack: 95,
        defense: 100,
        specialAttack: 115,
        special: "Robot rizz",
        speed:105,
        image: "images/i69.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Moon Knight",
        id: 70,
        weight: 102,
        height: `6'0”`,
        type: 'Sick Costume',
        hp: 95,
        attack: 105,
        defense: 90,
        specialAttack: 85,
        special: "Split personality final boss",
        speed:99,
        image: "images/i70.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Ant-Man",
        id: 71,
        weight: 86,
        height: `5'10”`,
        type: 'Small/big guy',
        hp: 90,
        attack: 85,
        defense: 80,
        specialAttack: 95,
        special: "Aquaman but with ants",
        speed:65,
        image: "images/i71.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Lex Luthor",
        id: 72,
        weight: 95,
        height: `6'2”`,
        type: 'Hater',
        hp: 100,
        attack: 85,
        defense: 100,
        specialAttack: 110,
        special: "Hate for Superman",
        speed:30,
        image: "images/i72.jpeg",
        uni:"DC"
    },
    {
        name: "Darkseid",
        id: 73,
        weight: 181,
        height: `8'0”`,
        type: 'Dark side',
        hp: 160,
        attack: 150,
        defense: 160,
        specialAttack: 170,
        special: "Wrong Speller",
        speed:120,
        image: "images/i73.jpeg",
        uni:"DC"
    },
    {
        name: "Harley Quinn",
        id: 74,
        weight: 63,
        height: `5'7”`,
        type: 'Woman',
        hp: 85,
        attack: 90,
        defense: 75,
        specialAttack: 85,
        special: "I can Fix Her",
        speed:20,
        image: "images/i74.jpeg",
        uni:"DC"
    },
    {
        name: "Bane",
        id: 75,
        weight: 180,
        height: `6'8”`,
        type: 'born in darkness',
        hp: 120,
        attack: 130,
        defense: 100,
        specialAttack: 70,
        special: "Hannibal lecter Mask",
        speed:70,
        image: "images/i75.jpeg",
        uni:"DC"
    },
    {
        name: "Riddler",
        id: 76,
        weight: 83,
        height: `6'1”`,
        type: 'Redditor',
        hp: 85,
        attack: 70,
        defense: 80,
        specialAttack: 110,
        special: "Awkwardness",
        speed:5,
        image: "images/i76.jpeg",
        uni:"DC"
    },
    {
        name: "Penguin",
        id: 77,
        weight: 95,
        height: `5'2”`,
        type: 'Mafia Boss',
        hp: 90,
        attack: 80,
        defense: 85,
        specialAttack: 95,
        special: "Can't fly",
        speed:80,
        image: "images/i77.jpeg",
        uni:"DC"
    },
    {
        name: "Two-Face",
        id: 78,
        weight: 97,
        height: `6'0”`,
        type: 'nice side, Ugly side',
        hp: 95,
        attack: 100,
        defense: 85,
        specialAttack: 90,
        special: "Heads dead tails bread",
        speed:55,
        image: "images/i78.jpeg",
        uni:"DC"
    },
    {
        name: "Scarecrow",
        id: 79,
        weight: 76,
        height: `6'0”`,
        type: 'british',
        hp: 85,
        attack: 75,
        defense: 70,
        specialAttack: 115,
        special: "Hides face with a sac",
        speed:55,
        image: "images/i79.jpeg",
        uni:"DC"
    },
    {
        name: "Poison Ivy",
        id: 80,
        weight: 61,
        height: `5'6”`,
        type: 'Gamora but better',
        hp: 90,
        attack: 85,
        defense: 85,
        specialAttack: 115,
        special: "star lord's type",
        speed:75,
        image: "images/i80.jpeg",
        uni:"DC"
    },
    {
        name: "Mr. Freeze",
        id: 81,
        weight: 90,
        height: `6'0”`,
        type: 'Broken Guy',
        hp: 100,
        attack: 90,
        defense: 100,
        specialAttack: 110,
        special: "Freezing Trauma",
        speed:45,
        image: "images/i81.jpeg",
        uni:"DC"
    },
    {
        name: "Black Cat",
        id: 82,
        weight: 135,
        height: `5'10”`,
        type: 'spiderman Options',
        hp: 95,
        attack: 100,
        defense: 85,
        specialAttack: 90,
        special: "Luck is no power",
        speed:85,
        image: "images/i82.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Catwoman",
        id: 83,
        weight: 61,
        height: `5'7”`,
        type: 'Woman Batman',
        hp: 85,
        attack: 95,
        defense: 80,
        specialAttack: 80,
        special: "Woman Abilities",
        speed:95,
        image: "images/i83.jpeg",
        uni:"DC"
    },
    {
        name: "Owlman",
        id: 84,
        weight: 95,
        height: `6'2”`,
        type: 'Nihilism Final Boss',
        hp: 100,
        attack: 110,
        defense: 95,
        specialAttack: 100,
        special: "Destroying Universes",
        speed:100,
        image: "images/i84.jpeg",
        uni:"DC"
    },
    {
        name: "Hela",
        id: 85,
        weight: 100,
        height: `6'2”`,
        type: 'Typical Big Sister',
        hp: 120,
        attack: 115,
        defense: 100,
        specialAttack: 125,
        special: "Kneel",
        speed:100,
        image: "images/i85.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Silver Surfer",
        id: 86,
        weight: 101,
        height: `6'4”`,
        type: 'Aura Famer',
        hp: 115,
        attack: 110,
        defense: 105,
        specialAttack: 130,
        special: "Heralding Galactus",
        speed:150,
        image: "images/i86.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Dormammu",
        id: 87,
        weight: 500,
        height: `7'0”`,
        type: 'Galactus Small cousin',
        hp: 130,
        attack: 115,
        defense: 110,
        specialAttack: 140,
        special: "Earth Lover",
        speed:`∞`,
        image: "images/i87.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Ego the Living Planet",
        id: 88,
        weight: 999999,
        height: `Planet-Sized`,
        type: 'Bad Parent',
        hp: 150,
        attack: 120,
        defense: 140,
        specialAttack: 135,
        special: "pregnancy",
        speed:`∞`,
        image: "images/i88.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Invincible",
        id: 89,
        weight: 170,
        height: `5'11”`,
        type: "Writer's Punching Bag",
        hp: 95,
        attack: 100,
        defense: 90,
        specialAttack: 95,
        special: "Eve",
        speed:120,
        image: "images/i89.jpeg",
        uni:"INVINCIBLE"
    },
    {
        name: "Miles Morales",
        id: 90,
        weight: 160,
        height: `5'8”`,
        type: 'Awkward Spiderman',
        hp: 105,
        attack: 105,
        defense: 95,
        specialAttack: 110,
        special: "Say Something Dumb",
        speed:102,
        image: "images/i90.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Spider-Gwen",
        id: 91,
        weight: 140,
        height: `5'7”`,
        type: 'Depression',
        hp: 100,
        attack: 100,
        defense: 95,
        specialAttack: 105,
        special: "Lover from Another World",
        speed:100,
        image: "images/i91.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Spider Punk",
        id: 92,
        weight: 167,
        height: `5'10”`,
        type: 'Coolest Spiderman',
        hp: 102,
        attack: 110,
        defense: 95,
        specialAttack: 100,
        special: "Rebellious",
        speed:90,
        image: "images/i92.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Spiderman 2099",
        id: 93,
        weight: 170,
        height: `5'10”`,
        type: 'Seriousness Final Boss',
        hp: 108,
        attack: 115,
        defense: 100,
        specialAttack: 110,
        special: "Spiderman with least Spider Powers",
        speed:105,
        image: "images/i93.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Spider Noir",
        id: 94,
        weight: 175,
        height: `6'0”`,
        type: 'Black and White',
        hp: 105,
        attack: 110,
        defense: 105,
        specialAttack: 95,
        special: "Rubicks Cube",
        speed:99,
        image: "images/i94.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Spider Ham",
        id: 95,
        weight: 55,
        height: `3'6”`,
        type: 'Goofiness',
        hp: 90,
        attack: 85,
        defense: 80,
        specialAttack: 100,
        special: "Spider Bitten By a Radioactive Pig",
        speed:90,
        image: "images/i95.jpeg",
        uni:"SPIDER VERSE"
    },
    {
        name: "Green Lantern",
        id: 96,
        weight: 195,
        height: `6'2”`,
        type: 'Bad Movie',
        hp: 95,
        attack: 90,
        defense: 90,
        specialAttack: 110,
        special: "who the hell has fear of Yellow",
        speed:105,
        image: "images/i96.jpeg"
    },
    {
        name: "Black Adam",
        id: 97,
        weight: 250,
        height: `6'3”`,
        type: "Shazam but without name issues",
        hp: 105,
        attack: 115,
        defense: 100,
        specialAttack: 90,
        special: "can't lose due to The Rock",
        speed:105,
        image: "images/i97.jpeg"
    },
    {
        name: "Adam Warlock",
        id: 98,
        weight: 240,
        height: `6'2”`,
        type: 'Comic Relief Character',
        hp: 110,
        attack: 100,
        defense: 95,
        specialAttack: 120,
        special: "Dumb kid in Adult Form",
        speed:110,
        image: "images/i98.jpeg",
        uni:"MARVEL"
    },
    {
        name: "Kingpin",
        id: 99,
        weight: 450,
        height: `6'7”`,
        type: 'Fat Ass',
        hp: 100,
        attack: 95,
        defense: 105,
        specialAttack: 70,
        special: "Dead wife which hates you",
        speed:80,
        image: "images/i99.jpeg",
        uni:"SPIDER VERSE/MARVEL"
    },
    {
        name: "Stan Lee",
        id: 100,
        weight: "∞",
        height: "∞",
        type: "The Creator",
        hp: "∞",
        attack: "∞",
        defense: "∞",
        specialAttack: "∞",
        special: "Cameos",
        speed:`∞`,
        image: "images/stan.jpeg",
        uni:"EARTH"
    }
];

